"""Initial schema: vector extension, users, media_items, media_structure_units

Revision ID: 0001
Revises:
Create Date: 2026-07-31

Written by hand rather than autogenerated. Autogenerate does not emit the
``vector`` extension, and it renders the deferrable unique constraint that
ADR-0006 depends on as an ordinary one — a difference that is invisible until a
renumbering transaction aborts in production.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector is enabled now, in the first migration, even though no embedding
    # column exists until M3. Enabling an extension needs privileges that a
    # later migration may not have on a managed host, and finding that out at
    # M3 is worse than a no-op line here.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("is_demo", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
    )
    op.create_index("ix_users_is_demo", "users", ["is_demo"])

    # VARCHAR + CHECK rather than a native ENUM type: ADR-0003 expects new media
    # types, and widening a CHECK is an ordinary migration where
    # ALTER TYPE ADD VALUE is not.
    # create_constraint=True is required: SQLAlchemy 2.0 defaults it to False,
    # which produces a bare VARCHAR enforced only by the ORM.
    media_type = sa.Enum(
        "book",
        name="media_type",
        native_enum=False,
        create_constraint=True,
        length=20,
    )

    op.create_table(
        "media_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("media_type", media_type, nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("structure_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_media_items_user_id_users",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_media_items"),
    )
    op.create_index("ix_media_items_user_id", "media_items", ["user_id"])
    op.create_index("ix_media_items_user_id_media_type", "media_items", ["user_id", "media_type"])

    op.create_table(
        "media_structure_units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("media_item_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "unit_type",
            sa.Enum(
                "chapter",
                "episode",
                "scene",
                "segment",
                name="unit_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.String(length=500), nullable=False),
        sa.Column("first_lines", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
            name="fk_media_structure_units_media_item_id_media_items",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_media_structure_units"),
    )

    # DEFERRABLE, per ADR-0006. Postgres validates uniqueness per row, so a bulk
    # renumber transiently duplicates an ordinal and would abort under an
    # immediate constraint. Alembic's create_unique_constraint cannot express
    # this, hence raw DDL.
    op.execute(
        """
        ALTER TABLE media_structure_units
        ADD CONSTRAINT uq_media_structure_units_media_item_id_ordinal
        UNIQUE (media_item_id, ordinal)
        DEFERRABLE INITIALLY IMMEDIATE
        """
    )

    op.create_index(
        "ix_media_structure_units_media_item_id_ordinal",
        "media_structure_units",
        ["media_item_id", "ordinal"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_media_structure_units_media_item_id_ordinal",
        table_name="media_structure_units",
    )
    op.drop_table("media_structure_units")

    op.drop_index("ix_media_items_user_id_media_type", table_name="media_items")
    op.drop_index("ix_media_items_user_id", table_name="media_items")
    op.drop_table("media_items")

    op.drop_index("ix_users_is_demo", table_name="users")
    op.drop_table("users")

    # The vector extension is deliberately not dropped. Other schemas may use
    # it, and dropping an extension is not the inverse of `IF NOT EXISTS`.
